#!/usr/bin/env bash
# 安装 dsh-desktop-pets 联动插件到 DSH web profile（与 vision-bridge 同款注册方式）：
#   1) 把本插件以 file: 依赖写进 ~/.dsh/profiles/web/package.json
#   2) 在 ~/.dsh/profiles/web/cordis.patch.yml 里 insert 插件条目
# 之后重启 `dsh web` 生效（插件加载后写 /tmp/desktop-pets-dsh.loaded 自检标记）。
set -u

PROFILE_DIR="$HOME/.dsh/profiles/web"
PLUGIN_NAME="dsh-desktop-pets"
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$PROFILE_DIR/package.json"
PATCH="$PROFILE_DIR/cordis.patch.yml"

if [ ! -f "$PKG" ]; then
  echo "[dsh-desktop-pets] 错误: 未找到 $PKG（DSH web profile 不存在？）"
  exit 1
fi

# 1) package.json dependencies 加入 file: 依赖（幂等：已存在则跳过）
if /usr/bin/python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); deps=d.setdefault("dependencies",{}); sys.exit(0 if deps.get(sys.argv[2]) else 1)' "$PKG" "$PLUGIN_NAME" 2>/dev/null; then
  echo "[dsh-desktop-pets] dependencies 已有 $PLUGIN_NAME，跳过"
else
  /usr/bin/python3 - "$PKG" "$PLUGIN_NAME" "$PLUGIN_DIR" <<'PY'
import json, sys
pkg_path, name, plugin_dir = sys.argv[1], sys.argv[2], sys.argv[3]
with open(pkg_path) as f:
    pkg = json.load(f)
deps = pkg.setdefault("dependencies", {})
deps[name] = "file:" + plugin_dir
with open(pkg_path, "w") as f:
    json.dump(pkg, f, ensure_ascii=False, indent=2)
    f.write("\n")
PY
  echo "[dsh-desktop-pets] 已写入 dependencies: $PLUGIN_NAME -> file:$PLUGIN_DIR"
fi

# 2) cordis.patch.yml insert 插件条目（幂等：已存在同名 id 则跳过）
if grep -q "id: $PLUGIN_NAME" "$PATCH" 2>/dev/null; then
  echo "[dsh-desktop-pets] $PATCH 已有 $PLUGIN_NAME，跳过"
else
  cat >> "$PATCH" <<EOF

# --- dsh-desktop-pets managed (auto-generated by integration/dsh-plugin/install.sh) ---
- insert:
    - id: $PLUGIN_NAME
      name: dsh-desktop-pets
# --- end dsh-desktop-pets managed ---
EOF
  echo "[dsh-desktop-pets] 已写入 $PATCH insert 条目"
fi

echo ""
echo "[dsh-desktop-pets] 安装完成。接下来："
echo "  1) cd $PROFILE_DIR && pnpm install    # 安装 file: 依赖"
echo "  2) 重启 dsh web"
echo "  3) 自检: ls -l /tmp/desktop-pets-dsh.loaded"
echo "  提示: 活动桌宠由 ~/.config/desktop-pets.json（或 ~/.config/opencode/desktop-pets.json）的 active 决定"
